---
- hosts: ec2-3-85-122-116.compute-1.amazonaws.com
  become: true
  become_method: sudo 
  vars:
    a: ec2-user
  tasks:
   - name: running date
     shell: date
   - name: create folder
     file:
       path: /tmp/balaji
       state: directory
  

