---
- name: install java
  yum:
   name: 
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
   state: present
   
- name: download the tomcat war file
  get_url:
   url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
   dest: /opt/
   
- name: create the tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    
- name: untar the tomcat
  shell: "tar -xzvf /opt/apache-tomcat-8.5.61.tar.gz -C /opt/tomcat/ --strip-components=1"
  
- name: create the tomcat group
  group: name=tomcat state=present
  
- name: create the tomcat user and add it to tomcat group
  user: name=tomcat group=tomcat state=present shell=/bin/bash home=/home/tomcat createhome=yes
  
- name: change the permissions
  shell: "chmod -R 755 /opt/tomcat/"
  
- name: change the ownership
  shell: "chown -R tomcat:tomcat /opt/tomcat"
  
  
- name: tomcat service file
  get_url:
    url: https://devops2020.s3.amazonaws.com/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    
- name: enable the service
  shell: "systemctl enable tomcat"
    
- name: daemon reload
  shell: "systemctl daemon-reload"
  
- name: start the tomcat
  shell: "systemctl start tomcat"
