---
# tasks file for tomcatest
- name : stop tomcat
  shell: "systemctl stop tomcat"
  
- name : Get the war file from artifactory
  get_url:
     url: "https://chbalaji080186.jfrog.io/artifactory/libs-snapshot-local/application1/application1-1.0.22.war"
     dest: /tmp/
     username: "balaji2003engg@gmail.com"
     password: "Ch683212@"
     
- name : copy the war to the webapps folder
  copy:
     src: /tmp/application1-1.0.22.war
     dest: /opt/tomcat/webapps/application1-1.0.22.war
     remote_src: yes
     
#- name : copy the tomcat service file 
 # template:
    #src: "roles/tomcat/templates/tomcat.service.j2"
   # dest: "/etc/systemd/system/tomcat.servcie"
  #  remote_src: yes

- name : enable the service
  shell: "systemctl enable tomcat"
  
- name : daemon reload
  shell: "systemctl daemon-reload"
 
- name : start the tomcat 
  shell: "systemctl start tomcat"

