---
# tasks file for tomcatdeployment
- name: Get the war to the temp location
  get_url:
    url: "{{jfrogurl}}/artifactory/{{jfrogrepo[env]}}/{{project}}/{{project}}-{{version}}.war"
    dest: /tmp/
    username: "{{jfrogusername}}"
    password: "{{jfrogpassword}}"
    
- name: stop the tomcat
  shell: systemctl stop tomcat
  
- name: copy the war file to the webapps folder
  copy:
    src: /tmp/{{project}}-{{version}}.war
    dest: /opt/tomcat/webapps/{{project}}.war
    remote_src: yes
    
- name: copy the tomcat service file
  template:
    src: "roles/tomcatdeployment/templates/tomcat.service.j2"
    dest: /etc/systemd/system/tomcat.service
    remote_src: yes
    
- name: start the tomcat
  shell: systemctl start tomcat
